dbs:
  - dir: /rails/storage
    pattern: "*.sqlite3"
    recursive: true
    replica:
      type: s3
      endpoint: ${AWS_ENDPOINT}
      bucket: pasabaya-backups
      path: database
      region: auto