l0-retention-check-interval: 4h
dbs:
  - path: /rails/storage/production.sqlite3
    replicas:
      - type: s3
        endpoint: ${AWS_ENDPOINT}
        bucket: pasabaya-backups
        path: database
        region: auto
        sync-interval: 1m
